# Generated by Django 4.1.9 on 2023-05-05 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(max_length=255)),
                ('privacy_type', models.CharField(choices=[('NC', 'Data Not Collected'), ('NL', 'Data Not Linked To You'), ('L', 'Data Linked To You'), ('T', 'Data Used To Track You')], default='NC', max_length=255)),
                ('data_category', models.CharField(choices=[('B', 'Browsing History'), ('CI', 'Contact Info'), ('C', 'Contacts'), ('D', 'Diagnostics'), ('F', 'Financial Info'), ('H', 'Health and Fitness'), ('I', 'Identifiers'), ('L', 'Location Info'), ('O', 'Other Data'), ('P', 'Purchases'), ('SH', 'Search History'), ('SI', 'Sensitive Info'), ('UD', 'Usage Data'), ('UC', 'User Content')], max_length=255)),
            ],
        ),
    ]
