# Generated by Django 4.1.9 on 2023-05-31 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='privacy_type',
            field=models.CharField(choices=[('NC', 'Data Not Collected'), ('NL', 'Data Not Linked To You'), ('L', 'Data Linked To You'), ('T', 'Data Used To Track You')], max_length=255),
        ),
    ]
