# Generated by Django 4.1.9 on 2023-05-31 18:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_app_data_type_app_purpose_alter_app_data_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='release_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
