# Generated by Django 4.1.9 on 2023-05-31 18:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_app_release_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='app_url',
            field=models.URLField(default=None),
        ),
        migrations.AddField(
            model_name='app',
            name='version_release_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
