# Generated by Django 4.1.9 on 2023-05-31 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0005_app_app_url_app_version_release_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='data_category',
            field=models.CharField(choices=[('B', 'Browsing History'), ('CI', 'Contact Info'), ('C', 'Contacts'), ('D', 'Diagnostics'), ('F', 'Financial Info'), ('H', 'Health and Fitness'), ('I', 'Identifiers'), ('L', 'Location Info'), ('O', 'Other Data'), ('P', 'Purchases'), ('SH', 'Search History'), ('SI', 'Sensitive Info'), ('UD', 'Usage Data'), ('UC', 'User Content')], default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='app',
            name='data_type',
            field=models.CharField(choices=[('AD', 'Advertising Data'), ('AU', 'Audio Data'), ('B', 'Browsing History'), ('CL', 'Coarse Location'), ('C', 'Contacts'), ('CD', 'Crash Data'), ('CI', 'Credit Info'), ('CS', 'Customer Support'), ('D', 'Device ID'), ('E', 'Email Address'), ('ET', 'Emails or Text Messages'), ('F', 'Fitness'), ('G', 'Gameplay Content'), ('H', 'Health'), ('N', 'Name'), ('PI', 'Payment Info'), ('PD', 'Performance Data'), ('PN', 'Phone Number'), ('PV', 'Photos or Videos'), ('PA', 'Physical Address'), ('PL', 'Precise Location'), ('PR', 'Product Interaction'), ('PH', 'Purchase History'), ('SH', 'Search History'), ('SI', 'Sensitive Info'), ('U', 'User ID'), ('O', 'Other')], default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='app',
            name='privacy_type',
            field=models.CharField(choices=[('NC', 'Data Not Collected'), ('NL', 'Data Not Linked To You'), ('L', 'Data Linked To You'), ('T', 'Data Used To Track You')], default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='app',
            name='purpose',
            field=models.CharField(choices=[('A', 'Analytics'), ('AP', 'App Functionality'), ('D', "Developer's Advertising or Marketing"), ('O', 'Other Purposes'), ('P', 'Product Personalization'), ('T', 'Third-party Advertising')], default=None, max_length=255),
        ),
    ]
