# Generated by Django 4.1.9 on 2023-06-01 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0006_alter_app_data_category_alter_app_data_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='app_url',
            field=models.URLField(blank=True, default=None),
        ),
    ]
